apiVersion: apps/v1
kind: Deployment
metadata:
  name: goalixa
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "core-api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "core-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "core-api.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: core-api
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.container.port }}
          env:
            - name: LOG_LEVEL
              value: {{ .Values.env.LOG_LEVEL | quote }}
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: DATABASE_URL
          volumeMounts:
            - name: data
              mountPath: /app/data
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: auth-data
