image:
  registry: harbor.goalixa.com
  repository: core-api/app
  tag: "latest"
  pullPolicy: Always

imagePullSecrets:
  - name: harbor-pull

replicaCount: 1

container:
  port: 80

env:
  LOG_LEVEL: "INFO"

service:
  type: ClusterIP
  port: 80

persistence:
  enabled: true
  storageClass: local-path
  accessMode: ReadWriteOnce
  size: 5Gi

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

autoscaling:
  enabled: false

namespace:
  name: core-api
